sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ICVtnASZis4W21jvl2zHsAakcTzZ+NQuYgwWW2b+vh2KWsfL2IW6zNZACYTJOvItquE1Xy/nBg2+7JzmiTOMsFiPSb5lbDFXvm+ZuUxPus1djd1OIu/gckiYGV9UNNA65YnTjO5fmKgdpAF2edJXqp5JLH9NQ5QbH1GlWj4DgZejmNsYFyEclHScAuEZSOfyn8vm5w1sBpe3NKk3Z3Go637XHnkBWj8MNB0K9C21eFPyHqWY2C7MPb66n9DqPyc4acSmPDcdBEysgbfwbyv3HPT7lDP+06JyiPuIxPuYwPr7WhFmRfA/WmdS6edZoUblcvGb31dFLJ1MqQ+rpvhRPjPSuXRYYOa25BSRZ/5wezolw+qJ66l4N8Iq5La6b4jL5zEt75u8TISvGhGvaBKYqCKkQaRz+P2YMvCReeO2BHL+feJGIxVYt/UJFPnmblbcPK1S5MaZ8UKYJzGe1VnNKFriPcmnLjZg4cibl9J+ygBX/v6PsltR1fjJwip+snoq+Oka6K9gsDA4kVxjdi26thcV5uRmvUXbc+BYOY8Ba48xX2CLbsGjBKgw4o3FEGn9Dtu4Mpc8UNKVVO59FrV9oOG6tNqigilby2bJv4urGpJ+WqGYxBmTVypBYrO4xjeu8lAr8u65XbRe4UvGF9Oa+e6D0pJPaujoCoXzqEzZxPE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Saunterings_3128
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy